# Generated by Django 5.2.15 on 2026-06-06 07:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mentor_profile', serialize=False, to='users.userprofile')),
                ('experience_yrs', models.SmallIntegerField()),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_url', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
