# Generated by Django 5.2.15 on 2026-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('learner', 'Learner'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='learner', max_length=20),
        ),
    ]
